# This workflow will deploy a MuleSoft project with Maven to PRD

name: Deploy to PRD

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The release version you want to deploy:"
        required: true
        type: string

jobs:
  mule:
    uses: galpenergia-integration/mulesoft-workflows-library/.github/workflows/CD-workflow.yml@main
    secrets: inherit
    # **************************************** DEVELOPERS ARE RESPONSIBLE IN MANAGING PARAMETERS BELOW THIS LINE **************************************************************
    with:
      # **************************************** MULE RUNTIME PROPERTIES ********************************************************************************************************           
      groupId: com.galp.mule
      artifactName: mulesoft-template-domain-example-layer
      version: ${{ inputs.version }}
      muleVersion: 4.4.0
      workers: 2
      workerType: MICRO
      applicationName: mulesoft-template-domain-example-layer-v1
      objectStoreV2: true
      persistentQueues: false
      businessGroupId: 688ff8b9-13db-44cb-b398-72735b227900
      environment: PRD
      envConfig: prd
      disableCloudhubLogs: false
      apiLayer: System
      deploymentTimeout: 120000                                                            
      anypointPlatformAnalyticsAgentEnabled: true
